### ISSUE TITLE
`tell` method in actor is not working with sleep

### ISSUE THREAD

**Issue by windbird123** [softwaremill/ox#110]
The following code was not working as expected. (ox version: 0.0.24)

```scala
import ox.supervised
import ox.channels.*

class Stateful:
  private var counter: Int = 0

  def increment(delta: Int): Int =
    counter += delta
    Thread.sleep(100)
    println(counter)
    counter

supervised {
  val ref = Actor.create(new Stateful)
  ref.tell(_.increment(5))
}
```

expected results: prints 5
actual results: prints nothing

When Thread.sleep(100) line was removed, it worked as expected.

**Comment by adamw** [comment]
You're right, the example in the docs is misleading. 

What happens there is that because `.tell` is non-blocking, the invocation is scheduled, and the scope ends (there's not other code to run - the main body is complete). When this happens, all threads that are still running (which includes actors) are interrupted. Hence, the `println` is never invoked.

**Comment by windbird123** [comment]
Thank you for your kind explanation.

When I replace `Thread.sleep(100)` with `(1 to 10000000).foreach(println)`, it seemed like there was no interruption. (It printed all numbers)

```scala
 def increment(delta: Int): Int =
    counter += delta
    // Thread.sleep(100)
    (1 to 10000000).foreach(println)
    println(counter)
    counter
```

I thought that `(1 to 10000000).foreach(println)` to be interrupted since the scope already ends (and main body is complete).
In this case, could we assume that ox tried to interrupt but was not interrupted.

**Comment by adamw** [comment]
Interesting! This surprised me as well, but it seems `println` is not interruptible!

You can observe the interruption e.g. as follows:

```
    def increment(delta: Int): Int =
      counter += delta
      try Thread.sleep(100)
      catch
        case e: Exception =>
          println("Exception: " + e)
          throw e
      println(counter)
      counter
```

**Comment by adamw** [comment]
I've expanded the example (https://github.com/softwaremill/ox/commit/4542e475a10ea733b7c3f785426108aca1a5fa8e), I'll close this for now as I think the code is fine, but please reopen if there are some more problems with `tell`
