### ISSUE TITLE
Rate control primitives?

### ISSUE THREAD

**Issue by windymelt** [softwaremill/ox#120]
Hi! At first, thank you for great async library! I tried examples and played exercises using documentation. It was full of fun!

My suggestion is providing rate control primitives (e.g. simple rate limit, smart (leaky bucket / token bucket) algorithm).

Sometimes I want rate control in production concurrent programming (e.g. batch processing along HTTP API).

Of course, we can implement simple control using `par()` and `Source.tick()`. But in production use, I think out-of-the-box rate control primitives is preferred.

**Comment by adamw** [comment]
Thanks! Definitely, rate control is something that will be great to include, and very much in-line with the scope of the project, in the "resiliency" part.

**Comment by adamw** [comment]
Just as Ox has `repeat` and `retry`, the goal here is to implement a rate limiter. Similarly to other resilience operation, this should come with a configuration object. 

Rate limiting itself should be possible in a stateful way, e.g. given a `RateLimiter.apply(=> T): T` method, which will block if the rate limit is reached. But we're open to any other suggestions.

As to the rate limiting configuration options, the algorithm mentioned in the original description should be available. Moreover, [resilience4j](https://resilience4j.readme.io/docs/ratelimiter) might provide more inspiration.

**Comment by adamw** [comment]
As we are getting first PRs for the bounties, I've published our ["How to prepare a good PR" guide](https://softwaremill.community/t/how-to-prepare-a-good-pr-to-a-library/448). I should have probably done this right away, sorry! :)
