### ISSUE TITLE
Add Either[Throwable, T]-unwrapping methods

### ISSUE THREAD

**Issue by adamw** [softwaremill/ox#203]
For situations when the left-side of an either should become a "panic" / bug.

Maybe: `myEither.!` - and then rename `.ok()` to `myEither.?` (when used within a bound)
Or: `myEither.orThrow()`

**Comment by adamw** [comment]
cc @lbialy maybe some bikeshedding? ;)

**Comment by adamw** [comment]
I'll go with `.orThrow` for now, but I'm not abandoning the idea of `.?` and `.!` ;)

**Comment by lbialy** [comment]
Oh, we're back to this discussion! I did not change my opinion on this and would definitely prefer `.?` and `.!` over `.ok?` and `.orThrow` :) It's a flow control structure, like send and ask in akka.
