### ISSUE TITLE
`timeout` behaviour when computation fails

### ISSUE THREAD

**Issue by nimatrueway** [softwaremill/ox#211]
```scala
timeout(1.second) {
  throw new Throwable("failed computation")
}
```

Currently, `timeout` is implemented using `race` which results in a behaviour where in the face of computation failure the block still waits until the timeout timer kicks in and the block fails with a timeout exception.

```scala
// currently: throws after 1 second
TimeoutException(s"Timed out after 1 second")
```

I believe though, the typical expectation of `timeout` is to quickly fail the block with the same exception as the failed computation throws and do not wait for the timeout timer to trigger.

```scala
// expected: immediately throw
Throwable("failed computation")
```

I'm pretty confident that we are aligned on this, so I'll prepare a small PR

**Comment by adamw** [comment]
Of course, you are right - thank you :)
