### ISSUE TITLE
The `race` function doesn't handle functions that can throw a `ControlThrowable` exception

### ISSUE THREAD

**Issue by rcardin** [softwaremill/ox#213]
I'm the maintainer of the library `raise4s`(link to the repo [here](https://github.com/rcardin/raise4s)). I use context functions to let the user declare functions that can raise logic-typed errors instead of exceptions. Jon Pretty is doing something close to my library with [Contingency](https://soundness.dev/contingency/).

I'd love to integrate with `ox` and write code like the following:

```scala 3
@main
def main(): Unit = {

  val result: Int raises String = ox.race(
    {
      ox.sleep(500.milliseconds)
      println("short task")
      Raise.raise("Something went wrong")
      2
    }, {
      ox.sleep(1.second)
      println("long task")
      Raise.raise("Something went wrong too late")
      1
    }
  )

  Raise.run(result) match {
    case value: Int => println(s"Value: $value")
    case error: String => println(s"Error: $error")
  }
}
```

However, the above code doesn't work. In detail, the execution of the `race` function never stops.

The implementation of the `raise` method uses the following exception:

```scala 3
private[raise4s] case class Raised[Error](original: Error)
    extends ControlThrowable
    with NoStackTrace
```

However, the implementation of the `ox.race` function handles the execution of the given lambdas through a `Try`:

```scala 3
fs.foreach(f => forkUnsupervised(result.put(Try(f()))))
```

Unfortunately, the `Try` type doesn't handle exceptions extending `ControlThrowable`. You can find [here](https://contributors.scala-lang.org/t/nonfatal-and-controlthrowable-changed-in-stdlib/6049/1) more details.

I already tried changing the `ox` code locally to add the handling of `ControlThrowable,` and everything started to integrate smoothly.

Can I open a PR to address the problem? Would you like to chat about it first?

**Comment by adamw** [comment]
Hey - sure, a PR would be great. Definitely we don't want any situations where Ox's code just "hangs". Worst case it should throw at least *some* exception. So maybe that's a wider problem, but let's start with `race`.
