### ISSUE TITLE
Composable retry policies

### ISSUE THREAD

**Issue by rucek** [softwaremill/ox#58]
The current retry mechanism allows to provide a single policy for retrying the operation. Once this policy is "exhausted", i.e. when it's done retrying without success, it gives up.

We'd like to be able to compose multiple policies, so that more than one can be tried in the attempt to run the operation. For example, we might want to make a couple of immediate retries (with no delay) and, if still unsuccessful, retry indefinitely with exponential backoff. 

The above could be written with a hypothetical `fallbackTo` combinator like:
```scala
val policy: RetryPolicy = RetryPolicy.immediate(3).fallbackTo(RetryPolicy.backoffForever(100.millis))
```

**Comment by zkerriga** [comment]
Hi, @rucek! I made solution to compose Schedules so we can construct policies like:
```scala
RetryPolicy(Schedule.Immediate(1).fallbackTo(Schedule.Delay(2, 2.seconds)))

RetryPolicy(Schedule.Delay(2, 1.second).fallbackTo(Schedule.Backoff.forever(2.seconds)))
```
but I am not sure about the design of it. Please, have a look at my request
