### ISSUE TITLE
Consider supporting Scala 2.13

### ISSUE THREAD

**Issue by altrack** [softwaremill/ox#61]
Hey SoftwareMill,

Since the introduction of project Loom there is a lot of interest in going back to direct style code from monads. Yet, most of the industry is still using Scala 2. Structured concurrency and scoped values will be probably GA in one of the next JVM versions, much sooner than the industry will move to Scala 3 (if at all).
Please consider adding Scala 2.13 support.

Thanks.

**Comment by lbialy** [comment]
Scala 2.13 support can't be easily added because context functions are a Scala 3 feature. Closest thing would be:
```scala
supervised { implicit Ox =>
  fork {
    
  }
}
```
Btw why would you want to use a new library with new jdk (21+) with an older version of the language? Are you stuck on 2.13 for some reason?

**Comment by altrack** [comment]
Databricks, Kafka-streams.

**Comment by adamw** [comment]
Cross compiling would require a lot of effort on our side, as we are using a lot of Scala 3 features in the library. It would also mean that Scala 2 Ox would have worse DX. So we'll keep it on Scala 3 only, leveraging Scala 3 and Java 21 to as much as possible.
