### ISSUE TITLE
scoped question

### ISSUE THREAD

**Issue by Richie-Jang** [softwaremill/ox#7]
Hello..
I have one question scoped function for learning the library.

for example of java =>
  var scope = new StructuredTaskScope.ShutdownOnFailure()
  scope.fork(() -> // long time take task )
  scope.fork(() -> exception happened)
  scope.join()
  scope.throwIfFailed()

the second task has an exception, the first task can be cancelled.

But in ox library, scoped function, 
  I need to set up two forks join.

How do I code same as java example?
If one of fork raises the exception, I need to cancel the other forks.

Thank you in advance.
Best Regards,
Richie.

**Comment by adamw** [comment]
You're right - the example doesn't translate directly. It's preferrable to use one of the higher-level functions, such as `par` or `race`, if possible. Your example would translate more or less to:

```scala
par({ /* long task */})({ /* throw exception */})
```

If you need some custom  behavior, you can always implement your own `par` variant - it's not as succint as creating two forks, but still quite short: https://github.com/softwaremill/ox/blob/290b8db8922aec3b6394f24141589ee9e7ff97b4/core/src/main/scala/ox/par.scala#L20-L29

Or maybe it would be a good candidate to include in Ox as a combinator?

**Comment by adamw** [comment]
Btw. note that the `fork` + `join` + `throwIfFailed` sequence is quite error prone - you need to invoke these methods in exactly this order. The ox approach, while might be less flexible in some cases, avoids such traps.

**Comment by Richie-Jang** [comment]
Thank you for detail explanation.
